language: php

php:
  - 7.0
  - 7.2

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'

# phpunit testing is disabled as dist vendor is cleared by removing unneeded files
#script:
#  - vendor/bin/phpunit